### PR TITLE
Renaming tasks to steps

### PR DESCRIPTION
**Pull request by max-radin**

### CODE REVIEW

**Review by martamau — COMMENTED** [review]
Shouldn't we change it to `_step` or maybe find an alternative?

**Comment by max-radin** [comment]
Good point! I renamed it to `_step`. Another option could be to name the function `run_psi4` and import the underlying function as something else, like `from qepsi4 import run_psi4 as _run_psi4`. But I think this might get confusing.

**Review by martamau — APPROVED** [review]
Nice. In the other resources, I think I decided to use slightly different name for the step instead of adding _step...I guess this might be something to decide once and for all before the release?

**Comment by max-radin** [comment]
Yes would be good to be consistent. Let's chat tomorrow!

**Pull request merged**
